### ISSUE TITLE
Import highlights not working

### ISSUE THREAD

**Issue by thelazyoxymoron** [theBenForce/logseq-plugin-my-highlights#19]
**Logseq version:** 0.7.5
**plugin version:** 1.16.0

Clicking on "Load Clippings File" opens up the file picker, but no action afterwards when the selection is done.

**Comment by petrushy** [comment]
Can confirm this bug on both linux & windows, logseq: 0.7.9

**Comment by theBenForce** [comment]
I'm able to reproduce now, so hopefully I can get it fixed.

**Comment by Gitbreast** [comment]
@theBenForce Problem's still there. Even have tried reload, reinstall the plugin, turn off other plugins. Here's the gif:
![Logseq_bALSMc630S](https://user-images.githubusercontent.com/96460796/185537103-b6010d98-b197-43f8-b96f-103beb607fbd.gif)

Plus: The plugin was worked early before(when I first time install), so that maybe could rule out the file system problem(where I storage the MyClipping.txt)and even the format recognize problem? Just in case, here's a screenshot about the format inside my clipping flie. Though it's in Chinese it should be has no difference with English version.
![image](https://user-images.githubusercontent.com/96460796/185539924-8cd1b9ff-2ed8-4309-bdd3-8c50af52c794.png)

**Comment by theBenForce** [comment]
@Gitbreast could you share a few highlights from your clippings file? That may help me reproduce the issue.

**Comment by Gitbreast** [comment]
@theBenForce Sure! Here's the end part of my clippings. [My Clippings part.txt](https://github.com/theBenForce/logseq-plugin-my-highlights/files/9381958/My.Clippings.part.txt)
How I got this file is: I copy the original file from my KP3, then delete about 9/10 of it, then ctrl+s and rename.
So that avoid changing the encode or something like that. BTW now it's this: ![image](https://user-images.githubusercontent.com/96460796/185616793-4a9d621f-21b8-4410-b99a-501fb3bc24b0.png)

**Comment by theBenForce** [comment]
Thank you! I found the issue, it's because I'm looking for markers like "Location" and "Added on". I'll try to come up with a more robust way of parsing the metadata, but for now I'll just make sure it can parse without finding the metadata.
