### ISSUE TITLE
Some possible enhancements

### ISSUE THREAD

**Issue by Gitbreast** [theBenForce/logseq-plugin-my-highlights#33]
1. Perhaps add a Google Images cover crawler is a good idea. I used to search metadatas and covers in Calibre, the Google Images seems like the most powerful cover download engine which the books cover are sooo many that every book could find its cover(especially in Non-English languages). Calibre searches the title and author in Google Images and picks up the top 20 for user to choose, which guarantees the quantity, the accurancy and the quality.

_Search Url Exp from Calibre_
```
https://www.google.com/search?as_st=y&tbm=isch&as_q=Sword+of+Destiny+%28The+Witcher+%232%29+Andrzej+Sapkowski&as_epq=&as_oq=&as_eq=&cr=&as_sitesearch=&safe=images&tbs=isz:lt,islt:svga,iar:t,ift:jpg
```
_P1: The Logs in Calibre_
![image](https://user-images.githubusercontent.com/96460796/186062950-783e3287-e16d-4827-9cac-5d1a684d33d6.png)
_P2: Results: Top 20 covers_
![image](https://user-images.githubusercontent.com/96460796/186063950-52c71474-53f8-4f0e-98b7-230eaf96324f.png)

2. Is it possible and useful to add a progress bar for showing the import progress so that avoid the user be anxious to close Logseq accidentally?

Plus, thanks for the fix about non-Enghlish importing. It works now but leave each block a long long highlight-id, and the icon before is changed.
![image](https://user-images.githubusercontent.com/96460796/186066668-b71dd9dd-29a3-4a27-8d15-bf33566018fd.png)

**Comment by theBenForce** [comment]
Thank you for the suggestions @Gitbreast!

1. If you hit next from the import dialog that page is pulling information from Amazon, but for some reason it doesn't work unless I'm testing the plugin. I used amazon because I can pull the ASIN and generate a link to open the book from the logseq page. Trying to find a workaround, logseq is locked down pretty tight.

![](https://github.com/theBenForce/logseq-plugin-my-highlights/raw/main/docs/sample_import.gif)

2. A progress bar is a great idea!

3. The [highlight-id can be hidden](https://github.com/theBenForce/logseq-plugin-my-highlights#hiding-highlight-id-properties). Right now it's using the ❓ since it can't detect if it's a note or highlight. I'll add an option to let you select the default type.

**Comment by theBenForce** [comment]
Created issues #34 and #35 to track suggested enhancements.

**Comment by Gitbreast** [comment]
@theBenForce Thanks for the tip! I successfully hid the highlight-id, it looks better now. For suggestion 1, "locked down pretty tight" sounds like Logseq's api or something like that limiting the develop? I'll wait and see if the plugin could pull my books' covers from Amazon correctly in later version, for now I could just paste the cover as an easy alter. Because the number of books limited by reading speed, copy and paste metadata is already fast enough compared to that. XD
